:: Generated by vinca http://github.com/RoboStack/vinca.
:: DO NOT EDIT!
setlocal EnableDelayedExpansion

:: Rattler-build will not set the SRC_DIR anymore so we set it through templating
set "SRC_DIR=@SRC_DIR@"

set "BUILD_DIR=@BUILD_DIR@"
set "BUILD_TYPE=@BUILD_TYPE@"

set "PYTHONPATH=%LIBRARY_PREFIX%\lib\site-packages;%SP_DIR%"

:: MSVC is preferred.
set CC=cl.exe
set CXX=cl.exe

:: Create build directory when not available
if not exist "%BUILD_DIR%" mkdir "%BUILD_DIR%"
pushd %BUILD_DIR%

set "CMAKE_GENERATOR=Ninja"
:: We use the Visual Studio generator as a workaround for
:: problems in Ninja when using long paths, see https://github.com/RoboStack/ros-humble/pull/229#issuecomment-2564856467
:: Once those are solved, we can switch back to use Ninja
:: set "CMAKE_GENERATOR=Visual Studio %VS_MAJOR% %VS_YEAR%"

:: PYTHON_INSTALL_DIR is passed as an absolute path with forward slashes.
::
:: The ament_cmake_python README suggests a relative path, but a relative value
:: such as ../Lib/site-packages makes CMake record the literal
:: "%LIBRARY_PREFIX%/../Lib/site-packages/..." in install_manifest.txt. That
:: manifest is appended verbatim to %RATTLER_BUILD_PACKAGE_FILES% below, and the
:: package writer rejects archive entries containing "..":
::   paths in archives must not have `..` when setting path for Library
::
:: A backslash absolute path is not an option either: it ends up in the
:: generated cmake_install.cmake and breaks its string parsing
:: (Invalid character escape '\b').
set "PYTHON_INSTALL_DIR=%SP_DIR:\=/%"

cmake ^
    -G "%CMAKE_GENERATOR%" ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
    -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=True ^
    -DPYTHON_EXECUTABLE=%PYTHON% ^
    -DPython_EXECUTABLE=%PYTHON% ^
    -DPython3_EXECUTABLE=%PYTHON% ^
    -DSETUPTOOLS_DEB_LAYOUT=OFF ^
    -DBUILD_SHARED_LIBS=ON ^
    -DBUILD_TESTING=OFF ^
    -DCMAKE_OBJECT_PATH_MAX=255 ^
    --compile-no-warning-as-error ^
    -DPYTHON_INSTALL_DIR=%PYTHON_INSTALL_DIR% ^
    %SRC_DIR%
if errorlevel 1 exit 1

:: We explicitly pass %CPU_COUNT% to cmake --build as we are not using Ninja,
:: see the comment before setting the CMAKE_GENERATOR env variable
cmake --build . --config Release --parallel %CPU_COUNT% --target install
if errorlevel 1 exit 1

:: `cmake --install` only copies files, it never removes them, so a prefix reused
:: by an incremental build still holds the files of the previous build.
type install_manifest.txt >>"%RATTLER_BUILD_PACKAGE_FILES%"
if errorlevel 1 exit 1
