# Generated by pixi-build-ros (ament_idl).
# Same CMake build as ament_cmake, plus a synthesized package.xml inside a
# work-dir-local source copy. rosidl_cmake's rosidl_generate_interfaces()
# hard-requires a package.xml declaring
#   <member_of_group>rosidl_interface_packages</member_of_group>
# Since pixi-native doesn't have one in the source tree, we fabricate a
# minimal one here from the project model.
set -eo pipefail

BUILD_DIR=@BUILD_DIR@
BUILD_TYPE=@BUILD_TYPE@

# Stage source into a work-dir-local copy and add the synthesized
# package.xml. Keeps the user's source tree clean (no stray file to gitignore,
# no concurrent-build races).
STAGE_DIR="$PWD/idl_src"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
# `cp -a .` so we copy contents (incl. dotfiles) without nesting an extra dir.
cp -a @SRC_DIR@/. "$STAGE_DIR/"

cat > "$STAGE_DIR/package.xml" <<'__PIXI_NATIVE_PACKAGE_XML__'
@PACKAGE_XML_CONTENT@
__PIXI_NATIVE_PACKAGE_XML__

if [ ! -d "$BUILD_DIR" ]; then
    mkdir -p "$BUILD_DIR"
fi
pushd $BUILD_DIR

# necessary for correctly linking SIP files (from python_qt_bindings)
export LINK=$CXX

if [[ $CONDA_BUILD_CROSS_COMPILATION != "1" ]]; then
    PYTHON_EXECUTABLE=$PREFIX/bin/python
    PKG_CONFIG_EXECUTABLE=$PREFIX/bin/pkg-config
    export QT_HOST_PATH="$PREFIX"
else
    PYTHON_EXECUTABLE=$BUILD_PREFIX/bin/python
    PKG_CONFIG_EXECUTABLE=$BUILD_PREFIX/bin/pkg-config
    export QT_HOST_PATH="$BUILD_PREFIX"
fi

OSX_DEPLOYMENT_TARGET="11.0"

if [[ $target_platform =~ linux.* ]]; then
    export CFLAGS="${CFLAGS} -D__STDC_FORMAT_MACROS=1"
    export CXXFLAGS="${CXXFLAGS} -D__STDC_FORMAT_MACROS=1"
fi

export ROS_PYTHON_VERSION=3
export PY_VER=${ROS_PYTHON_VERSION}
export PYTHON_INSTALL_DIR=$(realpath --relative-to="$PREFIX" "$SP_DIR")

if [ ! -f "build.ninja" ]; then
    cmake \
        -G "Ninja" \
        -S "$STAGE_DIR" \
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
        -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_PREFIX_PATH=$PREFIX \
        -DAMENT_PREFIX_PATH=$PREFIX \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE \
        -DPython_EXECUTABLE=$PYTHON_EXECUTABLE \
        -DPython3_EXECUTABLE=$PYTHON_EXECUTABLE \
        -DPython3_FIND_STRATEGY=LOCATION \
        -DPKG_CONFIG_EXECUTABLE=$PKG_CONFIG_EXECUTABLE \
        -DPYTHON_INSTALL_DIR=$PYTHON_INSTALL_DIR \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_SKIP_TESTING=$SKIP_TESTING \
        -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=True \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTING=OFF \
        -DCMAKE_IGNORE_PREFIX_PATH="/opt/homebrew;/usr/local/homebrew" \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=$OSX_DEPLOYMENT_TARGET \
        --compile-no-warning-as-error \
        $EXTRA_CMAKE_ARGS \
        .
fi

cmake --build . --config $BUILD_TYPE --target install
