# Generated by vinca http://github.com/RoboStack/vinca.
# DO NOT EDIT!

set -eo pipefail

# Stage source into a work-dir-local copy. The package's committed package.xml
# is a normal source file, so the tar below carries it into the staged copy —
# setup.py declares package.xml as a data_files entry, so it must exist in the
# source tree at install time. Dependencies are resolved by pixi, not parsed
# from package.xml.
#
# In pixi-native mode @SRC_DIR@ is the user's manifest dir and $PWD is
# <SRC_DIR>/.pixi/build/work/.../work — STAGE_DIR therefore sits inside
# @SRC_DIR@ and a plain `cp -a SRC_DIR/. STAGE_DIR/` recurses into itself.
# Tar with excludes side-steps that and skips junk we don't want in the build.
STAGE_DIR="$PWD/src_stage"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
tar -C "@SRC_DIR@" --exclude=./.pixi --exclude=./.git -cf - . | tar -C "$STAGE_DIR" -xf -

export SRC_DIR="$STAGE_DIR"

pushd $SRC_DIR

# If there is a setup.cfg that contains install-scripts then we should not set it here
if [ -f setup.cfg ] && grep -q "install[-_]scripts" setup.cfg; then
    # Remove e.g. ros-humble- from PKG_NAME
    PKG_NAME_SHORT=${PKG_NAME#*ros-@DISTRO@-}
    # Substitute "-" with "_"
    PKG_NAME_SHORT=${PKG_NAME_SHORT//-/_}
    INSTALL_SCRIPTS_ARG="--install-scripts=$PREFIX/lib/$PKG_NAME_SHORT"
    echo "WARNING: setup.cfg not set, will set INSTALL_SCRIPTS_ARG to: $INSTALL_SCRIPTS_ARG"
    $PYTHON setup.py install --prefix="$PREFIX" --install-lib="$SP_DIR" $INSTALL_SCRIPTS_ARG --single-version-externally-managed --record=files.txt
    # Remove build artifacts from setup.py install
    rm -rf *.egg-info 2>/dev/null || true
    rm -rf build/ 2>/dev/null || true
else
    $PYTHON -m pip install . --no-deps -vvv
fi
