# Generated by pixi-build-ros.
# DO NOT EDIT — see crates/pixi_build_ros/templates/build_ament_cargo.sh in the
# pixi-build-ros source.

set -eo pipefail

pushd @SRC_DIR@

export ROS_DISTRO=@DISTRO@
export AMENT_PREFIX_PATH="$PREFIX"
export CMAKE_PREFIX_PATH="$PREFIX"

# Rust 1.85+ defaults to the `wild` linker which conda's gcc rejects.
# Force cargo to link via the conda C compiler.
if [ -n "${CC:-}" ]; then
  export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER="${CC}"
  export RUSTFLAGS="-C linker=${CC} ${RUSTFLAGS:-}"
fi

# cargo-ament-build wraps `cargo build` (or `cargo check` for pure libraries)
# and lays down the ament install layout under --install-base. Source code is
# copied to share/<pkg>/rust/ so downstream Rust crates can resolve path
# dependencies via AMENT_PREFIX_PATH.
cargo ament-build --install-base "$PREFIX" --release -- --locked --offline || \
  cargo ament-build --install-base "$PREFIX" --release --
