[package]
name = "fancy_display"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Easy conversion into a styled-object"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
console = { workspace = true }
