[package]
name = "pixi_variant"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "Defines variant values for conda-build variant configurations"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
pixi_build_types = { workspace = true, optional = true }
rattler_lock = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
