#:tombi toml-version = "v1.0.0"
# The Python packaging ecosystem parses this file with TOML 1.0 parsers

[project]
name = "detectron2-from-source"
version = "0.1.0"
description = "Build detectron2 from source and installs into pypi environment"
requires-python = ">= 3.11"
authors = [{ name = "Tim de Jager", email = "tim@prefix.dev" }]
dependencies = [
  "detectron2 @ git+https://github.com/facebookresearch/detectron2.git@bcfd464d0c810f0442d91a349c0f6df945467143",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tool.pixi.dependencies]
cxx-compiler = "1.7.*"
libgfortran = ">=15.1.0,<16"
ninja = ">=1, <=2"
pytorch = ">=2.4.0, <=3.0.0"
setuptools = ">=72, <=73"

[tool.pixi.pypi-options]
# Will build detectron2 and fvcore without isolation
# in the default environment
no-build-isolation = ["detectron2", "fvcore"]
