[package]
name = "pixi_build_types"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "The types for communicating between the pixi build frontend and backend"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
hex = { workspace = true }
ordermap = { workspace = true, features = ["serde"] }
pixi_stable_hash = { workspace = true, features = [
  "rattler_conda_types",
  "rattler_digest",
  "url",
] }
rattler_conda_types = { workspace = true }
rattler_digest = { workspace = true, features = ["serde"] }
schemars = { workspace = true, features = ["url2"], optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
