#:tombi toml-version = "v1.0.0"
# The Python packaging ecosystem parses this file with TOML 1.0 parsers

[project]
name = "root"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = ["depend"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "*" }

[tool.pixi.package.host-dependencies]
hatchling = ">=1.27,<2.0"

[tool.pixi.package.run-dependencies]
depend = { path = "../depend" }
