use std::{
    collections::HashSet,
    path::{Path, PathBuf},
};

use clap::Parser;
use miette::{Context, IntoDiagnostic};
use pixi_config::ConfigCli;
use pixi_core::{WorkspaceLocator, lock_file::UpdateLockFileOptions};
use pixi_manifest::PixiPlatformName;
use rattler_conda_types::{
    ExplicitEnvironmentEntry, ExplicitEnvironmentSpec, PackageRecord, Platform, RepoDataRecord,
};
use rattler_lock::{
    CondaPackageData, Environment, LockedPackage, Platform as LockedPlatform, PlatformName,
};

use crate::cli_config::{LockFileUpdateConfig, NoInstallConfig, WorkspaceConfig};

#[derive(Debug, Parser)]
#[clap(arg_required_else_help = false)]
pub struct Args {
    #[clap(flatten)]
    pub config_source: pixi_config::ConfigSourceCli,

    #[clap(flatten)]
    pub workspace_config: WorkspaceConfig,

    /// Output directory for rendered explicit environment spec files
    pub output_dir: PathBuf,

    /// The environments to render. Can be repeated for multiple environments.
    #[arg(short, long)]
    pub environment: Option<Vec<String>>,

    /// The platform to render. Can be repeated for multiple platforms.
    /// Accepts a workspace platform name; a bare conda subdir (e.g.
    /// `linux-64`) selects every workspace platform built for that subdir.
    /// Defaults to all platforms available for selected environments.
    #[arg(short, long)]
    pub platform: Option<Vec<PixiPlatformName>>,

    /// PyPI dependencies are not supported in the conda explicit spec file.
    #[arg(long, default_value = "false")]
    pub ignore_pypi_errors: bool,

    /// Source dependencies are not supported in the conda explicit spec file.
    #[arg(long, default_value = "false")]
    pub ignore_source_errors: bool,

    #[clap(flatten)]
    pub lock_file_update_config: LockFileUpdateConfig,

    #[clap(flatten)]
    pub no_install_config: NoInstallConfig,

    #[clap(flatten)]
    config: ConfigCli,
}

fn build_explicit_spec<'a>(
    platform: &Platform,
    conda_packages: impl IntoIterator<Item = &'a RepoDataRecord>,
) -> miette::Result<ExplicitEnvironmentSpec> {
    let mut packages = Vec::new();

    for cp in conda_packages {
        let prec = &cp.package_record;
        let hash = prec.md5.ok_or(miette::miette!(
            "Package {} does not contain an md5 hash",
            prec.name.as_normalized()
        ))?;

        let mut url = cp.url.clone();
        url.set_fragment(Some(&hex::encode(hash)));

        packages.push(ExplicitEnvironmentEntry {
            url: url.to_owned(),
        });
    }

    Ok(ExplicitEnvironmentSpec {
        platform: Some(*platform),
        packages,
    })
}

fn render_explicit_spec(
    target: impl AsRef<Path>,
    exp_env_spec: &ExplicitEnvironmentSpec,
) -> miette::Result<()> {
    if exp_env_spec.packages.is_empty() {
        return Ok(());
    }

    let target = target.as_ref();

    let mut environment = String::new();
    environment.push_str("# Generated by `pixi workspace export`\n");
    environment.push_str(exp_env_spec.to_spec_string().as_str());

    fs_err::write(target, environment)
        .into_diagnostic()
        .with_context(|| format!("failed to write environment file: {}", target.display()))?;

    Ok(())
}

/// Returns true if a `--platform` request selects `platform`.
///
/// A request matches the workspace platform name first (e.g. `x86-cuda13`) and
/// falls back to the conda subdir, so a bare `linux-64` selects *every*
/// workspace platform that builds for `linux-64`.
fn platform_matches(platform: &LockedPlatform<'_>, requested: &PixiPlatformName) -> bool {
    platform.name().as_str() == requested.as_str()
        || platform.subdir().as_str() == requested.as_str()
}

fn render_env_platform(
    output_dir: &Path,
    env_name: &str,
    env: &Environment,
    platform: LockedPlatform<'_>,
    ignore_pypi_errors: bool,
) -> miette::Result<()> {
    // Rich platforms (platforms carrying system-requirements) are named
    // independently of their conda subdir, and several of them can share one
    // subdir. Each is rendered to its own file keyed by platform name, while
    // the spec itself records the conda subdir it installs into.
    let platform_name: &PlatformName = platform.name();
    let subdir = platform.subdir();

    let packages = env.packages(platform).ok_or(miette::miette!(
        "platform '{platform_name}' not found for env {}",
        env_name,
    ))?;

    let mut conda_packages_from_lock_file: Vec<_> = Vec::new();

    for package in packages {
        match package {
            LockedPackage::Conda(CondaPackageData::Binary(p)) => {
                conda_packages_from_lock_file.push(p.clone())
            }
            LockedPackage::Conda(CondaPackageData::Source(_)) => {
                miette::bail!(
                    "Conda source packages are not supported in a conda explicit spec. \
                        Specify `--ignore-source-errors` to ignore this error and create \
                        a spec file containing only the binary conda dependencies from the lock file."
                );
            }
            LockedPackage::Pypi(pypi) => {
                if ignore_pypi_errors {
                    tracing::warn!(
                        "ignoring PyPI package {} since PyPI packages are not supported",
                        pypi.name()
                    );
                } else {
                    miette::bail!(
                        "PyPI packages are not supported in a conda explicit spec. \
                        Specify `--ignore-pypi-errors` to ignore this error and create \
                        a spec file containing only the conda dependencies from the lock file."
                    );
                }
            }
        }
    }

    // Topologically sort packages
    let repodata = conda_packages_from_lock_file
        .into_iter()
        .map(|p| RepoDataRecord::try_from(*p))
        .collect::<Result<Vec<_>, _>>()
        .into_diagnostic()
        .with_context(|| "Failed to convert conda packages to RepoDataRecords")?;

    let repodata = PackageRecord::sort_topologically(repodata);

    let ees = build_explicit_spec(&subdir, &repodata)?;

    tracing::info!("Creating conda explicit spec for env: {env_name} platform: {platform_name}");
    let target = output_dir
        .join(format!("{env_name}_{platform_name}_conda_spec.txt"))
        .into_os_string();

    render_explicit_spec(target, &ees)?;

    Ok(())
}

pub async fn execute(args: Args) -> miette::Result<()> {
    let workspace = WorkspaceLocator::for_cli()
        .with_global_config_source(args.config_source.source())
        .with_search_start(args.workspace_config.workspace_locator_start())
        .locate()?
        .with_cli_config(args.config.clone());

    let lock_file = workspace
        .update_lock_file(
            Some(pixi_reporters::TopLevelProgress::from_global()),
            UpdateLockFileOptions {
                lock_file_usage: args.lock_file_update_config.lock_file_usage()?,
                no_install: args.no_install_config.no_install,
                max_concurrent_solves: workspace.config().max_concurrent_solves(),
                ..Default::default()
            },
        )
        .await?
        .0
        .into_lock_file();

    let mut environments = Vec::new();
    if let Some(env_names) = args.environment {
        for env_name in &env_names {
            environments.push((
                env_name.to_string(),
                lock_file
                    .environment(env_name)
                    .ok_or(miette::miette!("unknown environment {}", env_name))?,
            ));
        }
    } else {
        for (env_name, env) in lock_file.environments() {
            environments.push((env_name.to_string(), env));
        }
    };

    let mut env_platform = Vec::new();

    for (env_name, env) in environments {
        let Some(ref requested_platforms) = args.platform else {
            env_platform.extend(env.platforms().map(|plat| (env_name.clone(), env, plat)));
            continue;
        };

        // A request can match more than one platform, and different requests
        // can match the same one (e.g. `linux-64` and `x86-cuda13`), so
        // deduplicate to render each platform exactly once.
        let mut selected = HashSet::new();
        for requested in requested_platforms {
            let matches = env
                .platforms()
                .filter(|plat| platform_matches(plat, requested))
                .collect::<Vec<_>>();

            if matches.is_empty() {
                tracing::warn!(
                    "Platform {} not available for environment {}. Skipping...",
                    requested,
                    env_name,
                );
                continue;
            }

            env_platform.extend(
                matches
                    .into_iter()
                    .filter(|plat| selected.insert(*plat))
                    .map(|plat| (env_name.clone(), env, plat)),
            );
        }
    }

    fs_err::create_dir_all(&args.output_dir).ok();

    for (env_name, env, plat) in env_platform {
        render_env_platform(
            &args.output_dir,
            &env_name,
            &env,
            plat,
            args.ignore_pypi_errors,
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use rattler_lock::LockFile;
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn test_render_conda_explicit_spec() {
        let path = Path::new(env!("CARGO_WORKSPACE_DIR"))
            .join("tests/data/mock-projects/test-project-export/pixi.lock");
        let lock_file = LockFile::from_path(&path).unwrap();

        let output_dir = tempdir().unwrap();

        for (env_name, env) in lock_file.environments() {
            for platform in env.platforms() {
                let platform_name = platform.name();
                // example contains pypi dependencies so should fail if `ignore_pypi_errors` is
                // false.
                assert!(
                    render_env_platform(output_dir.path(), env_name, &env, platform, false)
                        .is_err()
                );
                render_env_platform(output_dir.path(), env_name, &env, platform, true).unwrap();

                let file_path = output_dir
                    .path()
                    .join(format!("{env_name}_{platform_name}_conda_spec.txt"));
                insta::assert_snapshot!(
                    format!("test_render_conda_explicit_spec_{env_name}_{platform_name}"),
                    fs_err::read_to_string(file_path).unwrap()
                );
            }
        }
    }

    /// Loads the rich-platform fixture, which declares five platforms across
    /// three subdirs, two of which (`osx-arm64` and `linux-64`) are covered by
    /// more than one platform.
    fn rich_platforms_lock_file() -> LockFile {
        let path = Path::new(env!("CARGO_WORKSPACE_DIR"))
            .join("tests/data/mock-projects/test-project-export/pixi-rich-platforms.lock");
        LockFile::from_path(&path).unwrap()
    }

    #[test]
    fn test_render_conda_explicit_spec_rich_platforms() {
        let lock_file = rich_platforms_lock_file();

        let output_dir = tempdir().unwrap();

        for (env_name, env) in lock_file.environments() {
            for platform in env.platforms() {
                let platform_name = platform.name();
                render_env_platform(output_dir.path(), env_name, &env, platform, true).unwrap();

                let file_path = output_dir
                    .path()
                    .join(format!("{env_name}_{platform_name}_conda_spec.txt"));
                insta::assert_snapshot!(
                    format!("test_render_conda_explicit_spec_rich_{env_name}_{platform_name}"),
                    fs_err::read_to_string(file_path).unwrap()
                );
            }
        }
    }

    /// Names of the platforms a `--platform <requested>` selects, sorted so the
    /// assertions don't depend on the lock file's platform ordering.
    fn select_platforms(env: &Environment<'_>, requested: &str) -> Vec<String> {
        let requested = PixiPlatformName::try_from(requested).unwrap();
        let mut names: Vec<String> = env
            .platforms()
            .filter(|plat| platform_matches(plat, &requested))
            .map(|plat| plat.name().to_string())
            .collect();
        names.sort();
        names
    }

    #[test]
    fn test_platform_selection_by_subdir_matches_every_rich_platform() {
        let lock_file = rich_platforms_lock_file();
        let (_, env) = lock_file.environments().next().unwrap();

        // A bare conda subdir selects every platform built for that subdir,
        // not just the first one or the one literally named after the subdir.
        assert_eq!(
            select_platforms(&env, "osx-arm64"),
            vec!["osx-arm64-cuda", "osx-arm64-macos-14-0"]
        );
        assert_eq!(
            select_platforms(&env, "linux-64"),
            vec!["linux-64", "x86-cuda13"]
        );
        assert_eq!(select_platforms(&env, "win-64"), vec!["win-64"]);
    }

    #[test]
    fn test_platform_selection_by_name_matches_a_single_platform() {
        let lock_file = rich_platforms_lock_file();
        let (_, env) = lock_file.environments().next().unwrap();

        assert_eq!(select_platforms(&env, "x86-cuda13"), vec!["x86-cuda13"]);
        assert_eq!(
            select_platforms(&env, "osx-arm64-cuda"),
            vec!["osx-arm64-cuda"]
        );
        assert!(select_platforms(&env, "does-not-exist").is_empty());
    }
}
