[package]
name = "pixi_pty"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]

[target."cfg(unix)".dependencies]
libc = { workspace = true }
nix = { workspace = true, features = ["fs", "poll", "signal", "term"] }
signal-hook = { workspace = true }
