#:tombi toml-version = "v1.0.0"
# The Python packaging ecosystem parses this file with TOML 1.0 parsers

[project]
name = "package_with_extras"
version = "0.0.2"
description = "A small source package with extras"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "Nichita Morcotilo", email = "nmorkotilo@gmail.com" }]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
]

dependencies = ["boltons"]

[project.optional-dependencies]
cli = ["click"]
color = ["rich"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
