[package]
name = "pixi_glob"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "A crate to deal with globs in pixi"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
dashmap = { workspace = true }
fs-err = { workspace = true }
ignore = { workspace = true }
itertools = { workspace = true }
memchr = { workspace = true }
parking_lot = { workspace = true }
pixi_path = { workspace = true }
rattler_digest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
insta = { workspace = true, features = ["redactions", "yaml"] }
rstest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tempfile = { workspace = true }
