"""Generate Markdown reference documentation for the ``pixi.toml`` manifest."""

from __future__ import annotations

import sys
from enum import Enum
from pathlib import Path
from typing import Any, Union, get_args, get_origin

from pydantic import fields as pydantic_fields

from model import (
    Activation,
    BaseManifest,
    Build,
    BuildBackend,
    ChannelInlineTable,
    Environment,
    Feature,
    FindLinksPath,
    FindLinksURL,
    MatchspecTable,
    Package,
    PyPIOptions,
    PyPIVersion,
    PyPIGitBranchRequirement,
    PyPIGitTagRequirement,
    PyPIGitRevRequirement,
    PyPIPathRequirement,
    PyPIUrlRequirement,
    S3Options,
    SourceLocation,
    SystemRequirements,
    Target,
    TaskInlineTable,
    TaskArgs,
    DependsOn,
    Workspace,
    WorkspacePlatform,
    WorkspaceTarget,
    hyphenize,
)

HERE = Path(__file__).parent
OUTPUT_PATH = HERE.parent / "docs" / "reference" / "manifest_reference.md"

AUTOGEN_HEADER = "<!-- This file is autogenerated from schema/model.py. Do not edit manually! -->"

_FRIENDLY: dict[str, str] = {
    "NonEmptyStr": "string",
    "PositiveFloat": "number",
    "AnyHttpUrl": "URL",
    "AnyUrl": "URL",
    "PathNoBackslash": "path",
    "Md5Sum": "md5 string",
    "Sha256Sum": "sha256 string",
    "ExcludeNewer": "timestamp or duration",
    "ChannelName": "string or URL",
    "CondaPackageName": "string",
    "PyPIPackageName": "string",
    "EnvironmentName": "string",
    "FeatureName": "string",
    "SolveGroupName": "string",
    "TargetName": "string",
    "TaskName": "string",
    "TaskArgName": "string",
    "ExtraName": "string",
    "FlagName": "string",
    "PlatformName": "string",
    "Glob": "glob pattern",
    "UnsignedInt": "non-negative integer",
    "GitUrl": "git URL",
}


def friendly_type(annotation: Any) -> str:
    """Return a human-readable type string for a field annotation."""
    if annotation is None:
        return "any"

    for key, name in _FRIENDLY.items():
        if key in str(annotation):
            return name

    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)

    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " \\| ".join(f"`{e.value}`" for e in annotation)

    try:
        from typing import Literal
        if origin is Literal:
            return " \\| ".join(f"`{a}`" for a in get_args(annotation))
    except ImportError:
        pass

    if origin is Union:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return friendly_type(args[0])
        return " or ".join(friendly_type(a) for a in args)

    if origin is list:
        args = get_args(annotation)
        if args:
            return f"list of {friendly_type(args[0])}"
        return "list"

    if origin is dict:
        args = get_args(annotation)
        if len(args) == 2:
            return f"map of {friendly_type(args[0])} to {friendly_type(args[1])}"
        return "map"

    if isinstance(annotation, type):
        if hasattr(annotation, "model_fields"):
            return f"`{annotation.__name__}` object"
        return annotation.__name__

    if hasattr(annotation, "__metadata__"):
        inner = get_args(annotation)
        if inner:
            return friendly_type(inner[0])

    return str(annotation)


def is_required(field_info: pydantic_fields.FieldInfo) -> bool:
    if field_info.default is not pydantic_fields.PydanticUndefined:
        return False
    if field_info.default_factory is not None:
        return False
    return True


def model_to_table(model_class: type, skip: set[str] | None = None) -> str:
    """Generate a Markdown table documenting all fields of a Pydantic model."""
    skip = skip or set()
    lines = [
        "| Field | Type | Required | Description |",
        "|-------|------|----------|-------------|",
    ]

    for name, info in model_class.model_fields.items():
        if name in skip:
            continue
        display = info.alias or hyphenize(name)
        ftype = friendly_type(info.annotation)
        req = "yes" if is_required(info) else "no"
        desc = (info.description or "").replace("\n", " ").strip()
        lines.append(f"| `{display}` | {ftype} | {req} | {desc} |")

    return "\n".join(lines)


def section(title: str, model_class: type, description: str = "",
            skip: set[str] | None = None) -> str:
    """Generate a section with heading, optional description, and field table."""
    parts = [f"## {title}\n"]
    text = description or (model_class.__doc__ or "").strip()
    if text:
        parts.append(f"{text}\n")
    parts.append(model_to_table(model_class, skip=skip))
    parts.append("")
    return "\n".join(parts)


def generate() -> str:
    """Generate the complete manifest reference document."""
    out: list[str] = [AUTOGEN_HEADER, ""]

    out.append("# Manifest Reference\n")
    out.append(
        "Auto-generated reference of all fields in the `pixi.toml` manifest file. "
        "For a narrative guide with examples and best practices, "
        "see the [Pixi Manifest](pixi_manifest.md) documentation.\n"
    )

    out.append(section(
        "`[workspace]`", Workspace,
        "The workspace metadata: channels, platforms, and project identity.",
        skip={"target"},
    ))

    out.append(section(
        "`[workspace.platforms]` inline table entry", WorkspacePlatform,
        "When a platform entry is an inline table it can declare virtual packages.",
    ))

    out.append(section("Channel inline table", ChannelInlineTable))

    out.append(section(
        "`[dependencies]` — conda matchspec table", MatchspecTable,
        "Fields available when a conda dependency is specified as a table.",
    ))

    # PyPI dependencies
    out.append("## `[pypi-dependencies]`\n")
    out.append("PyPI dependencies can be a version string or one of several table forms.\n")
    for label, cls in [
        ("Version requirement", PyPIVersion),
        ("Path requirement", PyPIPathRequirement),
        ("URL requirement", PyPIUrlRequirement),
        ("Git branch requirement", PyPIGitBranchRequirement),
        ("Git tag requirement", PyPIGitTagRequirement),
        ("Git rev requirement", PyPIGitRevRequirement),
    ]:
        out.append(f"### {label}\n")
        out.append(model_to_table(cls))
        out.append("")

    out.append(section(
        "`[tasks]`", TaskInlineTable,
        "A task defined as an inline table. Tasks can also be plain command strings.",
    ))
    out.append(section("`[tasks]` arguments", TaskArgs))
    out.append(section("`[tasks]` depends-on entry", DependsOn))

    out.append(section(
        "`[system-requirements]`", SystemRequirements,
        "Platform-specific system requirements. "
        "Deprecated in favor of inline-table entries on `workspace.platforms`.",
    ))

    out.append(section("`[feature.<name>]`", Feature))
    out.append(section("`[environments.<name>]`", Environment))
    out.append(section("`[activation]`", Activation))
    out.append(section("`[target.<name>]`", Target))
    out.append(section("`[pypi-options]`", PyPIOptions))
    out.append(section("`[package]`", Package))
    out.append(section("`[package.build]`", Build))
    out.append(section("`[package.build.backend]`", BuildBackend))
    out.append(section("`[package.build.source]`", SourceLocation))
    out.append(section("`[workspace.s3-options.<bucket>]`", S3Options))
    out.append(section(
        "Top-level manifest fields", BaseManifest,
        "Fields at the root level of a `pixi.toml`, outside any specific table.",
        skip={"tool"},
    ))

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    content = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    kb = round(len(content) / 1024, 2)
    print(f"... wrote {kb}kb to {OUTPUT_PATH}", file=sys.stderr)
