"""Generate Markdown reference documentation for the ``pixi.toml`` manifest."""

from __future__ import annotations

import json
import sys
from enum import Enum
from pathlib import Path
from typing import Any, Union, get_args, get_origin

from pydantic import fields as pydantic_fields

from model import (
    Activation,
    BaseManifest,
    Build,
    BuildBackend,
    ChannelInlineTable,
    Environment,
    Feature,
    MatchspecTable,
    Package,
    PyPIOptions,
    PyPIVersion,
    PyPIGitBranchRequirement,
    PyPIGitTagRequirement,
    PyPIGitRevRequirement,
    PyPIPathRequirement,
    PyPIUrlRequirement,
    S3Options,
    SourceLocation,
    SystemRequirements,
    Target,
    TaskInlineTable,
    TaskArgs,
    DependsOn,
    Workspace,
    WorkspacePlatform,
    hyphenize,
)

HERE = Path(__file__).parent
OUTPUT_PATH = HERE.parent / "docs" / "reference" / "_schema_tables.txt"

AUTOGEN_HEADER = "<!-- This file is autogenerated from schema/model.py. Do not edit manually! -->"

_FRIENDLY: dict[str, str] = {
    "NonEmptyStr": "string",
    "PositiveFloat": "number",
    "AnyHttpUrl": "URL",
    "AnyUrl": "URL",
    "PathNoBackslash": "path",
    "Md5Sum": "md5 string",
    "Sha256Sum": "sha256 string",
    "ExcludeNewer": "timestamp or duration",
    "ChannelName": "string or URL",
    "CondaPackageName": "string",
    "PyPIPackageName": "string",
    "EnvironmentName": "string",
    "FeatureName": "string",
    "SolveGroupName": "string",
    "TargetName": "string",
    "TaskName": "string",
    "TaskArgName": "string",
    "ExtraName": "string",
    "FlagName": "string",
    "PlatformName": "string",
    "Glob": "glob pattern",
    "UnsignedInt": "non-negative integer",
    "GitUrl": "git URL",
}


def friendly_type(annotation: Any) -> str:
    """Return a human-readable type string for a field annotation."""
    if annotation is None:
        return "any"

    for key, name in _FRIENDLY.items():
        if key in str(annotation):
            return name

    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)

    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " \\| ".join(f"`{e.value}`" for e in annotation)

    try:
        from typing import Literal

        if origin is Literal:
            return " \\| ".join(f"`{a}`" for a in get_args(annotation))
    except ImportError:
        pass

    if origin is Union:
        args = [a for a in get_args(annotation) if a is not type(None)]
        if len(args) == 1:
            return friendly_type(args[0])
        return " or ".join(friendly_type(a) for a in args)

    if origin is list:
        args = get_args(annotation)
        if args:
            return f"list of {friendly_type(args[0])}"
        return "list"

    if origin is dict:
        args = get_args(annotation)
        if len(args) == 2:
            return f"map of {friendly_type(args[0])} to {friendly_type(args[1])}"
        return "map"

    if isinstance(annotation, type):
        if hasattr(annotation, "model_fields"):
            return f"`{annotation.__name__}` object"
        return annotation.__name__

    if hasattr(annotation, "__metadata__"):
        inner = get_args(annotation)
        if inner:
            return friendly_type(inner[0])

    return str(annotation)


def is_required(field_info: pydantic_fields.FieldInfo) -> bool:
    if field_info.default is not pydantic_fields.PydanticUndefined:
        return False
    if field_info.default_factory is not None:
        return False
    return True


def model_to_table(model_class: Any, skip: set[str] | None = None) -> str:
    """Generate a Markdown table documenting all fields of a Pydantic model."""
    skip = skip or set()
    lines = [
        "| Field | Type | Required | Description |",
        "|-------|------|----------|-------------|",
    ]

    for name, info in model_class.model_fields.items():
        if name in skip:
            continue
        display = info.alias or hyphenize(name)
        ftype = friendly_type(info.annotation)
        req = "yes" if is_required(info) else "no"
        desc = (info.description or "").replace("\n", " ").strip()

        examples = getattr(info, "examples", None)
        if examples:
            ex_strs = []
            for ex in examples:
                if isinstance(ex, (dict, list, bool)):
                    ex_strs.append(f"`{json.dumps(ex)}`")
                else:
                    ex_strs.append(f"`{ex}`")
            if ex_strs:
                desc += f"<br>**Examples:** {', '.join(ex_strs)}"

        lines.append(f"| `{display}` | {ftype} | {req} | {desc} |")

    return "\n".join(lines)


def section(snippet_name: str, model_class: Any, skip: set[str] | None = None) -> str:
    """Generate a snippet with a field table."""
    parts = [f"--8<-- [start:{snippet_name}]"]
    parts.append(model_to_table(model_class, skip=skip))
    parts.append(f"--8<-- [end:{snippet_name}]\n")
    return "\n".join(parts)


def generate() -> str:
    """Generate the complete manifest reference snippets."""
    out: list[str] = [AUTOGEN_HEADER, ""]

    out.append(section("workspace", Workspace, skip={"target"}))
    out.append(section("workspace_platforms", WorkspacePlatform))
    out.append(section("channel", ChannelInlineTable))
    out.append(section("dependencies", MatchspecTable))

    for label, cls in [
        ("pypi_version", PyPIVersion),
        ("pypi_path", PyPIPathRequirement),
        ("pypi_url", PyPIUrlRequirement),
        ("pypi_git_branch", PyPIGitBranchRequirement),
        ("pypi_git_tag", PyPIGitTagRequirement),
        ("pypi_git_rev", PyPIGitRevRequirement),
    ]:
        out.append(section(label, cls))

    out.append(section("tasks", TaskInlineTable))
    out.append(section("task_args", TaskArgs))
    out.append(section("task_depends_on", DependsOn))

    out.append(section("system_requirements", SystemRequirements))
    out.append(section("feature", Feature))
    out.append(section("environments", Environment))
    out.append(section("activation", Activation))
    out.append(section("target", Target))
    out.append(section("pypi_options", PyPIOptions))
    out.append(section("package", Package))
    out.append(section("package_build", Build))
    out.append(section("package_build_backend", BuildBackend))
    out.append(section("package_build_source", SourceLocation))
    out.append(section("s3_options", S3Options))
    out.append(section("base_manifest", BaseManifest, skip={"tool"}))

    return "\n".join(out) + "\n"


if __name__ == "__main__":
    content = generate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
    kb = round(len(content) / 1024, 2)
    print(f"... wrote {kb}kb to {OUTPUT_PATH}", file=sys.stderr)
