"""Ratchet for `into_diagnostic()` calls, see https://github.com/prefix-dev/pixi/issues/6707.

Library crates should return typed errors instead of converting into `miette::Report`.
Until the migration is done and this check is replaced by a clippy `disallowed-methods`
entry, the per-crate count of `into_diagnostic` outside `tests/` directories must match
the checked-in baseline exactly, so it can only go down.

Run with `--update` to rewrite the baseline.
"""

import subprocess
import sys
import tomllib
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent.parent
BASELINE = Path(__file__).parent / "into_diagnostic_baseline.toml"


def count() -> Counter[str]:
    out = subprocess.run(
        # `-o` prints one line per occurrence, so two calls on one line count twice
        ["git", "grep", "-o", "into_diagnostic", "--", "*.rs", ":(glob,exclude)**/tests/**"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    counts: Counter[str] = Counter()
    for line in out.stdout.splitlines():
        p = line.split("/")
        counts[p[1] if p[0] == "crates" else p[0]] += 1
    return counts


def main() -> None:
    current = count()
    if "--update" in sys.argv:
        lines = [f"{crate} = {n}" for crate, n in sorted(current.items())]
        BASELINE.write_text(
            "# Generated by `scripts/check_into_diagnostic.py --update`. Crates not listed are pinned at 0.\n"
            + "\n".join(lines)
            + "\n"
        )
        return

    baseline = tomllib.loads(BASELINE.read_text())
    diff = [
        f"  {crate}: {baseline.get(crate, 0)} -> {current[crate]}"
        for crate in sorted(current.keys() | baseline.keys())
        if current[crate] != baseline.get(crate, 0)
    ]
    if diff:
        sys.exit(
            "`into_diagnostic()` counts changed:\n"
            + "\n".join(diff)
            + "\n\nIf a count rose, return a typed error (a `thiserror` enum deriving"
            " `miette::Diagnostic`) instead, see https://github.com/prefix-dev/pixi/issues/6707."
            "\nIf it dropped, or the new call is a sanctioned edge (CLI top level, binaries'"
            " `main`, build backends), run `pixi run check-into-diagnostic --update` and commit"
            " the baseline."
        )


if __name__ == "__main__":
    main()
