"""
Generate a sitemap.xml template override listing all pages.

Zensical's built-in sitemap template only receives the pages that are part of
the navigation, which would drop the CLI reference from the sitemap. This
script scans the docs directory for all Markdown pages and writes a template
override that lists every page. The URLs are prefixed with the site URL at
render time, so that versioned builds with mike get the correct version
prefix. Run it after staging files into the docs directory; the override is
ignored by git.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
DOCS_DIR = REPO_ROOT / "docs"
TEMPLATE = DOCS_DIR / "overrides" / "sitemap.xml"

HEADER = """\
{#-
  This file was automatically generated by scripts/generate_sitemap.py.
  The site_url has no trailing slash when mike appends the docs version,
  so it is stripped before joining.
-#}
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{%- if config.site_url %}
{%- set base = config.site_url | trim("/") %}\
"""

FOOTER = """
{%- endif %}
</urlset>
"""


def page_path(page: Path) -> str:
    """Return the path a page is rendered to with directory URLs."""
    relative = page.relative_to(DOCS_DIR)
    parts = relative.parent.parts
    if relative.stem not in ("index", "README"):
        parts += (relative.stem,)
    return "".join(f"{part}/" for part in parts)


def main() -> None:
    entries = []
    for page in sorted(DOCS_DIR.rglob("*.md")):
        entries.append(f"\n  <url>\n    <loc>{{{{ base }}}}/{page_path(page)}</loc>\n  </url>")

    TEMPLATE.write_text(HEADER + "".join(entries) + FOOTER, encoding="utf-8")
    print(f"Generated {TEMPLATE.relative_to(REPO_ROOT)} with {len(entries)} pages")


if __name__ == "__main__":
    main()
