use clap::{Arg, Command, CommandFactory};
use fs_err as fs;
use itertools::Itertools;
use std::cmp::Ordering;
use std::collections::HashMap;
use std::error::Error;
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::process::exit;
use std::str::FromStr;

const MD_EXTENSION: &str = ".md";

/// Markers in `zensical.toml` between which the CLI navigation is written.
const NAV_START_MARKER: &str =
    "# The CLI nav below is generated by pixi_docs. Do not edit manually!";
const NAV_END_MARKER: &str = "# End of generated CLI nav.";

/// tombi's line width. The generated nav matches tombi's formatting so that
/// `tombi format` leaves it unchanged.
const LINE_WIDTH: usize = 80;

/// Generates documentation for the Pixi CLI by:
/// - Loading the clap command from the pixi crate
/// - Creating markdown files for each command
/// - Organizing commands into a directory structure
/// - Writing the navigation for these files into `zensical.toml`
fn main() -> Result<(), Box<dyn Error>> {
    let command = get_command();

    let output_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../docs/reference/cli");

    println!("Generating CLI documentation in {}", output_dir.display());

    process_subcommands(&command, Vec::new(), &output_dir)?;

    let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../zensical.toml");
    update_nav(&command, &manifest_path)?;

    Ok(())
}

/// Returns whether the command has subcommands that appear in the docs.
fn has_visible_subcommands(command: &Command) -> bool {
    command
        .get_subcommands()
        .any(|subcommand| !subcommand.is_hide_set())
}

/// Generates a TOML nav entry for a command, nesting visible subcommands.
/// Commands with subcommands become sections whose first entry is the
/// command's own `index.md` page, which `navigation.indexes` turns into a
/// clickable section header.
fn nav_entry(command: &Command, parents: &[String], indent: usize) -> Option<String> {
    if command.is_hide_set() {
        return None;
    }

    let name = command.get_name();
    let pad = "  ".repeat(indent);

    let visible: Vec<_> = command
        .get_subcommands()
        .filter(|subcommand| !subcommand.is_hide_set())
        .collect();
    if visible.is_empty() {
        let page = format!("reference/cli/{}/{name}{MD_EXTENSION}", parents.join("/"));
        // tombi measures the line without the trailing comma
        let single = format!("{pad}{{ \"{name}\" = \"{page}\" }}");
        if single.len() <= LINE_WIDTH {
            return Some(format!("{single},\n"));
        }
        return Some(format!(
            "{pad}{{\n{pad}  \"{name}\" = \"{page}\"\n{pad}}},\n"
        ));
    }

    let page = format!(
        "reference/cli/{}/{name}/index{MD_EXTENSION}",
        parents.join("/")
    );
    let mut buffer = String::new();
    writeln!(buffer, "{pad}{{").unwrap();
    writeln!(buffer, "{pad}  \"{name}\" = [").unwrap();
    writeln!(buffer, "{pad}    \"{page}\",").unwrap();
    let mut child_parents = parents.to_vec();
    child_parents.push(name.to_string());
    for subcommand in visible {
        if let Some(entry) = nav_entry(subcommand, &child_parents, indent + 2) {
            buffer.push_str(&entry);
        }
    }
    writeln!(buffer, "{pad}  ]").unwrap();
    writeln!(buffer, "{pad}}},").unwrap();
    Some(buffer)
}

/// Writes the CLI navigation between the markers in `zensical.toml`.
fn update_nav(command: &Command, manifest_path: &Path) -> Result<(), Box<dyn Error>> {
    let content = fs::read_to_string(manifest_path)?;

    let start_marker = content
        .find(NAV_START_MARKER)
        .ok_or("missing CLI nav start marker in zensical.toml")?;
    let nav_start = start_marker
        + content[start_marker..]
            .find('\n')
            .ok_or("missing newline after CLI nav start marker in zensical.toml")?
        + 1;
    let end_marker = content
        .find(NAV_END_MARKER)
        .ok_or("missing CLI nav end marker in zensical.toml")?;
    if end_marker < nav_start {
        return Err("CLI nav end marker precedes start marker in zensical.toml".into());
    }
    let nav_end = content[..end_marker].rfind('\n').map_or(0, |i| i + 1);

    // The markers sit three levels deep in the nav array, inside "Reference"
    let indent = 3;
    let pad = "  ".repeat(indent);
    let mut nav = String::new();
    writeln!(nav, "{pad}{{").unwrap();
    writeln!(nav, "{pad}  \"CLI\" = [").unwrap();
    writeln!(
        nav,
        "{pad}    \"reference/cli/{}/index{MD_EXTENSION}\",",
        command.get_name()
    )
    .unwrap();
    let parents = vec![command.get_name().to_string()];
    for subcommand in command.get_subcommands() {
        if let Some(entry) = nav_entry(subcommand, &parents, indent + 2) {
            nav.push_str(&entry);
        }
    }
    writeln!(nav, "{pad}  ]").unwrap();
    writeln!(nav, "{pad}}},").unwrap();

    let updated = format!("{}{}{}", &content[..nav_start], nav, &content[nav_end..]);
    fs::write(manifest_path, updated)?;

    println!("Updated CLI navigation in {}", manifest_path.display());

    Ok(())
}

/// Converts a command to Markdown format
fn subcommand_to_md(parents: &[String], command: &Command) -> String {
    let mut buffer = String::with_capacity(1024);

    // Generate title from command path
    let mut title_parts = parents.to_vec();
    title_parts.push(command.get_name().to_string());
    let title = title_parts.join(" ");

    // Write YAML frontmatter with title
    writeln!(buffer, "---").unwrap();
    writeln!(buffer, "title: {title}").unwrap();
    writeln!(buffer, "---").unwrap();

    // Start with autogenerated header
    // This is also used in the `ci.yml` to remove all the autogenerated files before running this script.
    writeln!(
        buffer,
        "<!--- This file is autogenerated. Do not edit manually! -->"
    )
    .unwrap();

    // Parent path for relative links
    let parent_path = if parents.is_empty() {
        "".to_string()
    } else {
        format!("{}/", parents.join("/"))
    };

    // Name with correct relative links including .md extension
    let mut name_parts = Vec::new();
    // Directory depth of this page below `reference/cli/`. Pages of commands
    // with subcommands live one directory deeper, as `index.md` in their own
    // directory.
    let dir_depth = parents.len() + usize::from(has_visible_subcommands(command));

    // Handle parents; every parent has subcommands, so its page is the
    // `index.md` of the directory named after it
    for (i, parent) in parents.iter().enumerate() {
        let ups = dir_depth - i - 1;
        let relative_path = format!("{}index.md", "../".repeat(ups));
        name_parts.push(format!("[{parent}]({relative_path}) "));
    }

    // Add current command without link
    name_parts.push(command.get_name().to_string());

    // Title
    writeln!(buffer, "# {}", name_parts.join("")).unwrap();

    // About
    if command.get_name() != "pixi" {
        if let Some(about) = command.get_about() {
            writeln!(buffer, "\n{about}").unwrap();
        }
    }

    // Additional description
    writeln!(
        buffer,
        "\n--8<-- \"docs/reference/cli/{}{}_extender:description\"",
        parent_path,
        command.get_name()
    )
    .unwrap();

    // Usage
    writeln!(buffer, "\n## Usage").unwrap();
    writeln!(buffer, "```").unwrap();
    {
        let mut command = command.clone();
        writeln!(
            buffer,
            "{}{}{}",
            parents.join(" "),
            if parents.is_empty() { "" } else { " " },
            command
                .render_usage()
                .to_string()
                .trim_start_matches("Usage: ")
        )
        .unwrap();
    }
    writeln!(buffer, "```").unwrap();

    // Subcommands
    if command.has_subcommands() {
        writeln!(buffer, "\n## Subcommands").unwrap();
        let subcommands: Vec<_> = command.get_subcommands().collect();
        if !subcommands.is_empty() {
            writeln!(
                buffer,
                "{}",
                subcommands_table(subcommands, command.get_name())
            )
            .unwrap();
        }
    }

    // Get a list of the parents and command name
    let mut parts = parents.to_vec();
    parts.push(command.get_name().to_string());

    // Positionals
    let positionals: Vec<_> = command.get_positionals().collect();
    if !positionals.is_empty() {
        writeln!(buffer, "\n## Arguments").unwrap();
        write!(buffer, "{}", arguments(&positionals, &parts)).unwrap();
    }

    // Options
    let opts: Vec<_> = command.get_opts().collect();
    if !opts.is_empty() {
        // All options with their header
        let header_option_map: HashMap<String, Vec<&Arg>> = opts
            .iter()
            .map(|o| {
                (
                    o.get_help_heading().unwrap_or("Options").to_string(),
                    o.to_owned(),
                )
            })
            .into_group_map();

        let sorted_header_options = header_option_map
            .iter()
            .sorted_by(|a, b| {
                match (a.0.as_str(), b.0.as_str()) {
                    // "Options" comes first
                    ("Options", _) => Ordering::Less,
                    (_, "Options") => Ordering::Greater,
                    // "Global Options" comes last
                    ("Global Options", _) => Ordering::Greater,
                    (_, "Global Options") => Ordering::Less,
                    // Alphabetical for others
                    _ => a.0.cmp(b.0),
                }
            })
            .filter_map(|(header, opts)| {
                // If all options are hidden, skip this header
                if opts.iter().all(|o| o.is_hide_set()) {
                    None
                } else {
                    Some((header, opts))
                }
            });

        for (header, opts) in sorted_header_options {
            writeln!(buffer, "\n## {header}").unwrap();
            write!(buffer, "{}", arguments(opts, &parts)).unwrap();
        }
    }

    // Long about
    if let Some(long) = command.get_long_about() {
        writeln!(buffer, "\n## Description").unwrap();
        writeln!(buffer, "{}\n", normalize_lists(long.to_string().trim_end())).unwrap();
    }

    // Write snippet link
    writeln!(
        buffer,
        "\n--8<-- \"docs/reference/cli/{}{}_extender:example\"",
        parent_path,
        command.get_name()
    )
    .unwrap();

    buffer
}

/// Returns the indentation of a line that starts a Markdown list item, or
/// `None` for any other line.
fn list_marker_indent(line: &str) -> Option<usize> {
    let content = line.trim_start();
    let indent = line.len() - content.len();

    let bullet = ["- ", "* ", "+ "]
        .iter()
        .any(|marker| content.starts_with(marker));
    let digits = content.chars().take_while(char::is_ascii_digit).count();
    let ordered =
        digits > 0 && (content[digits..].starts_with(". ") || content[digits..].starts_with(") "));

    (bullet || ordered).then_some(indent)
}

/// Rewrites lists so that the docs renderer recognizes them.
///
/// Doc comments write lists the way they should look in `--help`: indented, and
/// usually glued to the line that introduces them. The `mdx_truly_sane_lists`
/// extension the docs use only accepts a list whose markers sit at column zero
/// and that is preceded by a blank line - anything else becomes a paragraph of
/// run-together bullets. So every line of an indented list is shifted left by
/// the indentation of the marker that started it, which keeps nested items and
/// continuation lines intact, and a missing blank line is inserted in front.
fn normalize_lists(text: &str) -> String {
    let mut lines: Vec<&str> = Vec::new();
    // The indentation stripped from the lines of the list being walked over
    let mut list_indent: Option<usize> = None;

    for line in text.lines() {
        if line.trim().is_empty() {
            list_indent = None;
        } else if list_indent.is_none() {
            // Four spaces of indentation start a code block, not a list
            if let Some(indent) = list_marker_indent(line).filter(|indent| *indent < 4) {
                if lines
                    .last()
                    .is_some_and(|previous| !previous.trim().is_empty())
                {
                    lines.push("");
                }
                list_indent = Some(indent);
            }
        }

        let stripped = line
            .chars()
            .take(list_indent.unwrap_or(0))
            .take_while(|character| *character == ' ')
            .count();
        lines.push(&line[stripped..]);
    }

    lines.join("\n")
}

/// Processes a command and its subcommands, generating markdown documentation
fn process_subcommands(
    command: &Command,
    parent_path: Vec<String>,
    output_dir: &Path,
) -> Result<(), Box<dyn Error>> {
    if command.is_hide_set() {
        return Ok(());
    }

    let mut current_path = parent_path;
    current_path.push(command.get_name().to_string());

    // Commands with subcommands get the `index.md` of the directory holding
    // their subcommand pages, so that `navigation.indexes` renders them as
    // clickable section headers
    let command_file_name = if has_visible_subcommands(command) {
        format!("{}/index{MD_EXTENSION}", current_path.join("/"))
    } else {
        format!("{}{}", current_path.join("/"), MD_EXTENSION)
    };
    let command_file_path = output_dir.join(&command_file_name);

    fs::create_dir_all(command_file_path.parent().ok_or("Invalid path")?)
        .map_err(|e| format!("Failed to create directories: {e}"))?;
    fs::write(
        &command_file_path,
        subcommand_to_md(&current_path[..current_path.len() - 1], command),
    )
    .map_err(|e| {
        format!(
            "Failed to write command file {}: {}",
            command_file_path.display(),
            e
        )
    })?;

    for subcommand in command.get_subcommands() {
        process_subcommands(subcommand, current_path.clone(), output_dir)?;
    }

    Ok(())
}

/// Generates a Markdown table of subcommands with command names as links to their pages
fn subcommands_table(subcommands: Vec<&Command>, parent: &str) -> String {
    let mut buffer = String::with_capacity(1024);
    writeln!(buffer, "| Command | Description |").unwrap();
    writeln!(buffer, "|---------|-------------|").unwrap();
    for subcommand in subcommands {
        // Skip hidden subcommands
        if subcommand.is_hide_set() {
            continue;
        }

        let about = if let Some(about) = subcommand.get_about() {
            about
        } else {
            eprintln!(
                "Warning: Subcommand `{}{}` has no description",
                parent,
                subcommand.get_name()
            );
            exit(1);
        };
        // Create a link to the subcommand's Markdown file, relative to this
        // page's directory (the page of a command with subcommands is the
        // `index.md` of the directory holding its subcommand pages)
        let command_name = subcommand.get_name();
        let link = if has_visible_subcommands(subcommand) {
            format!("{command_name}/index{MD_EXTENSION}")
        } else {
            format!("{command_name}{MD_EXTENSION}")
        };
        let link_md = format!("[`{command_name}`]({link})");
        writeln!(buffer, "| {link_md} | {about} |",).unwrap();
    }
    buffer
}

// Function to write a list of options to the buffer
fn arguments(options: &[&clap::Arg], parents: &[String]) -> String {
    let mut buffer = String::with_capacity(1024);
    for opt in options {
        if opt.is_hide_set() ||
            // Skip short only as that is a bug in clap's disable help function.
            (opt.get_long().is_none() && opt.get_short().is_some())
        {
            continue;
        }

        let long_name = if let Some(long) = opt.get_long() {
            format!("--{long}")
        } else if let Some(value_names) = opt.get_value_names() {
            // No long name, but we have value names, assuming positional.
            format!("<{}>", value_names[0])
        } else {
            eprintln!(
                "Error: Option: '{:?}' with parents {} has no long name",
                opt,
                parents.join(" ")
            );
            exit(1);
        };

        // Error on missing help
        if opt.get_help().is_none() && opt.get_long().unwrap() != "help" {
            eprintln!(
                "Error: Option `{} {}` has no description",
                parents.join(" "),
                long_name
            );
            exit(1);
        }

        // Strip the angle brackets of positionals so that the id survives
        // Markdown rendering unescaped and the fragment link stays valid.
        let id = format!("arg-{}", long_name.trim_matches(['<', '>']));

        // Write the option as a bullet point with a self-referential <a> tag
        write!(
            buffer,
            "- <a id=\"{}\" href=\"#{}\">`{}{}{}`</a>\n:",
            id,
            id,
            long_name,
            if let Some(short) = opt.get_short() {
                format!(" (-{short})")
            } else {
                String::new()
            },
            if opt.get_action().takes_values() && !opt.is_positional() {
                if let Some(value_names) = opt.get_value_names() {
                    let sep = if opt.is_require_equals_set() {
                        "="
                    } else {
                        " "
                    };
                    format!("{}<{}>", sep, value_names.join(" "))
                } else {
                    String::new()
                }
            } else {
                String::new()
            }
        )
        .unwrap();

        // Write the help text
        if let Some(help) = opt.get_help() {
            writeln!(buffer, "  {help}").unwrap();
        } else {
            writeln!(buffer).unwrap();
        }

        // Write if it might be provided more than once
        if matches!(opt.get_action(), clap::ArgAction::Append) {
            writeln!(buffer, "<br>May be provided more than once.").unwrap();
        }

        // Add required
        if opt.is_required_set() {
            writeln!(buffer, "<br>**required**: `true`").unwrap();
        }

        // Handle aliases, env, defaults, and options
        if let Some(aliases) = opt.get_visible_aliases() {
            if !aliases.is_empty() {
                writeln!(buffer, "<br>**aliases**: {}", aliases.join(", ")).unwrap();
            }
        }
        if let Some(env) = opt.get_env() {
            writeln!(buffer, "<br>**env**: `{}`", env.to_string_lossy()).unwrap();
        }
        if !opt.get_default_values().is_empty() {
            writeln!(
                buffer,
                "<br>**default**: `{}`",
                opt.get_default_values()
                    .iter()
                    .map(|value| {
                        if rattler_conda_types::Platform::from_str(
                            value.as_os_str().to_str().unwrap(),
                        )
                        .is_ok()
                        {
                            "current_platform".to_string()
                        } else {
                            value.to_string_lossy().to_string()
                        }
                    })
                    .join(", ")
            )
            .unwrap();
        }
        if opt.get_action().takes_values() && !opt.get_possible_values().is_empty() {
            writeln!(
                buffer,
                "<br>**options**: `{}`",
                opt.get_possible_values()
                    .iter()
                    .map(|value| value.get_name())
                    .join("`, `")
            )
            .unwrap();
        }
    }
    buffer
}

/// Loads the CLI command structure from pixi
fn get_command() -> Command {
    pixi_cli::Args::command()
}

#[cfg(test)]
mod tests {
    use super::normalize_lists;

    #[test]
    fn dedents_a_list_and_separates_it_from_its_intro() {
        let text = "Destinations:\n  - prefix.dev: `https://prefix.dev/<channel>`\n  - local channel:\n    `file:///path` or a bare path\n\nTrailing paragraph.";
        assert_eq!(
            normalize_lists(text),
            "Destinations:\n\n- prefix.dev: `https://prefix.dev/<channel>`\n- local channel:\n  `file:///path` or a bare path\n\nTrailing paragraph."
        );
    }

    #[test]
    fn keeps_nested_items_nested() {
        let text = "  - outer\n    - inner\n  - outer again";
        assert_eq!(normalize_lists(text), "- outer\n  - inner\n- outer again");
    }

    #[test]
    fn leaves_a_well_formed_list_and_indented_code_alone() {
        let text = "Steps:\n\n1. first\n2. second\n\n    indented - code\n    - not a list";
        assert_eq!(normalize_lists(text), text);
    }
}
