[workspace]
channels = ["conda-forge"]
description = "A mock project that does ML stuff"
name = "multi-machine"
# The platforms fields can define custom platform features, like `cuda` and `osx` in this example.
# Use the field `name` to easily manage platform specific definitions.
platforms = [
    { name = "cuda-win-64", platform = "win-64", cuda = "12"},
    "win-64",
    { name = "cuda-linux-64", platform = "linux-64", cuda = "12" },
    "linux-64",
    { platform = "osx-arm64", macos = "13.5" },
]

[tasks]
start = { depends-on = ["train", "test"] }
test = "python test.py"
train = "python train.py"

[dependencies]
ipykernel = ">=7.2.0,<8"
matplotlib-base = ">=3.10.9,<4"
polars = ">=1.41.1,<2"
python = ">=3.13.13,<4"
torchvision = ">=0.26.0,<0.27"
pytorch = ">=2.10.0,<3"

[target.cuda-win-64.tasks]
test = "python test.py --cuda"
train = "python train.py --cuda"
[target.cuda-linux-64.tasks]
test = "python test.py --cuda"
train = "python train.py --cuda"

[target.osx.dependencies]
mlx = ">=0.20,<0.21"

[target.osx.tasks]
test = "python test.py --mlx"
train = "python train.py --mlx"
