[package]
name = "pypi_mapping"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "This crates maps PyPI packages to their corresponding Conda packages, using the parselmouth prefix project"
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-once-cell = { workspace = true }
async-trait = { workspace = true }
dashmap = { workspace = true }
fs-err = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-cache-reqwest = { workspace = true }
itertools = { workspace = true }
miette = { workspace = true }
pep440_rs = { workspace = true }
pep508_rs = { workspace = true }
rattler_conda_types = { workspace = true }
rattler_digest = { workspace = true }
rattler_networking = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
