name: release-gr
on:
  push:
    branches: [main]
jobs:
  release:
    uses: greenroom-robotics/ros_semantic_release_action/.github/workflows/recipes-release.yml@main
    with:
      package: pixi-build-ros-gr
      package_path: crates/pixi_build_ros
    secrets: inherit
